### ISSUE TITLE
The Witness crashes Frotz

### ISSUE THREAD

**Issue by eriktorbjorn** [AlexProudfoot/The-ZIL-Files#64]
Most inputs in the compiled version of The Witness crash Frotz for me. The problematic code seems to be somewhere in CLOCKER, because if I replace "<SET VAL <APPLY <GET .C ,C-RTN>>>" with "<SET VAL 0>" it doesn't crash for me.

I'm not suggesting that as a fix, of course. This was just my attempt at trying to figure out _where_ things went wrong. I still have no idea _why_, and it's unlikely that I'll be able to figure it out. I don't even know if it's a coding error in the game, or if there is some mis-compilation.

**Comment by jpcompton** [comment]
I confirm this behavior, compiling in zilf 0.8 produces an 117000 byte witness.z3 which dies in frotz with **Segmentation fault: 11** on basically any input.

_[...]The long week is finished, except for this appointment. But why does an ominous feeling grip you?

The WITNESS Infocom interactive fiction - a mystery story
Copyright (c) 1983 by Infocom, Inc. All rights reserved.
The WITNESS is a registered trademark of Infocom, Inc.
Release number 0 / Serial number 190604

You are now in the driveway entrance.
You are standing at the foot of the driveway, the entrance to the Linder property. The entire lot is screened from the street
and the neighbors by a wooden fence, except on the east side, which fronts on dense bamboo woods. The house looks like a mixture
of a California bungalow and East Asian influences. From here you can see the driveway leading north and, beyond that, the front
door.

What should you, the detective, do now?
>nSegmentation fault: 11_

**Comment by eriktorbjorn** [comment]
Though if the problem really is in CLOCKER, I'm not sure where. I don't see much functional difference between the ZAP code generated by ZILF 0.8:

```
        .FUNCT CLOCKER,C,E,TICK,FLG=0,VAL
        ZERO? CLOCK-WAIT /?L1
        SET 'CLOCK-WAIT,0
        RFALSE
?L1:    IGRTR? 'PRESENT-TIME,1199 \?L4
        CALL TIMES-UP
?L4:    IGRTR? 'MOVES,59 \?L9
        SET 'MOVES,0
        IGRTR? 'SCORE,23 \?L9
        SET 'SCORE,0
?L9:    ZERO? P-WON /?L13
        PUSH C-INTS
        JUMP ?L15
?L13:   PUSH C-DEMONS
?L15:   ADD C-TABLE,STACK >C
        ADD C-TABLE,C-TABLELEN >E
?L16:   EQUAL? C,E \?L18
        RETURN FLG
?L18:   GET C,C-ENABLED? >STACK
        ZERO? STACK /?L26
        GET C,C-TICK >TICK
        ZERO? TICK /?L26
        SUB TICK,1 >STACK
        PUT C,C-TICK,STACK
        GRTR? TICK,1 /?L26
        GET C,C-RTN >STACK
        CALL STACK >VAL
        ZERO? VAL /?L26
        ZERO? FLG /?L28
        EQUAL? VAL,M-FATAL \?L26
?L28:   SET 'FLG,VAL
?L26:   ADD C,C-INTLEN >C
        PUSH C
        JUMP ?L16
```

and the (probably) original ZAP code that can be found in Jason Scott's repository:

```
        .FUNCT  CLOCKER,C,E,TICK,FLG=0,VAL
        ZERO?   CLOCK-WAIT /?CND1
        SET     'CLOCK-WAIT,FALSE-VALUE
        RFALSE  
?CND1:  INC     'PRESENT-TIME
        GRTR?   PRESENT-TIME,1199 \?CND5
        CALL    TIMES-UP
?CND5:  IGRTR?  'MOVES,59 \?CND8
        SET     'MOVES,0
        IGRTR?  'SCORE,23 \?CND8
        SET     'SCORE,0
?CND8:  ZERO?   P-WON /?ELS18
        PUSH    C-INTS
        JUMP    ?CND14
?ELS18: PUSH    C-DEMONS
?CND14: ADD     C-TABLE,STACK >C
        ADD     C-TABLE,C-TABLELEN >E
?PRG22: EQUAL?  C,E \?ELS26
        RETURN  FLG
?ELS26: GET     C,C-ENABLED?
        ZERO?   STACK /?CND24
        GET     C,C-TICK >TICK
        ZERO?   TICK \?ELS31
        JUMP    ?CND24
?ELS31: SUB     TICK,1
        PUT     C,C-TICK,STACK
        GRTR?   TICK,1 /?CND29
        GET     C,C-RTN
        CALL    STACK >VAL
        ZERO?   VAL /?CND29
        ZERO?   FLG /?THN42
        EQUAL?  VAL,M-FATAL \?CND24
?THN42: SET     'FLG,VAL
?CND29: 
?CND24: ADD     C,C-INTLEN >C
        JUMP    ?PRG22
```

The ZAPF version has what looks like an unnecessary "PUSH C" near the end, but that's about it as far as I can tell. (At least assuming that ">STACK" is implied when nothing else is stated.) So I guess the problem could be in the data it operates on...?

**Comment by eriktorbjorn** [comment]
When it crashes for me - at least in Linux - it seems to be at PC 0x016A71 which, as far as I can tell, is at the very end of FOLLOW-GOAL. But since the crash happens when Frotz uses CODE_BYTE(opcode), and it's already done that numerous times at that same address before that, there has to be some memory corruption going on...

**Comment by eriktorbjorn** [comment]
It looks like it does get stuck in that FOLLOW-GOAL loop. I assume CNT grows out of bounds, and this eventually causes the failure. But why it does that... I'm afraid I've reached the limit of my ZIL debugging skills.

**Comment by eriktorbjorn** [comment]
As a side note, I tried adding a debug message to the corresponding function in Deadline, and I then just sat around waiting for the game to end. At worst, I saw CNT reach a little over 20. In the Witness, it reached well over 10000 before it crashed.

**Comment by taradinoc** [comment]
Try building the latest ZILF from source... there are some bugs in 0.8 that might be causing this. The big one is that it doesn't handle collisions between local and global names well, and The Witness has a lot of those.

**Comment by eriktorbjorn** [comment]
> Try building the latest ZILF from source...

Unfortunately, that will at the very least have to wait. Contrary to what others have said, I have yet to get even 0.8 to run under Mono in Linux, so I've only ever been able to run it at my work computer.

Perhaps someone else could give it a try?

**Comment by taradinoc** [comment]
> I have yet to get even 0.8 to run under Mono in Linux

ZILF has been ported to .NET Core for the 0.9 release, so it should be much easier to build on Linux these days. The SDK download has everything: https://dotnet.microsoft.com/download/dotnet-core/2.2

**Comment by eriktorbjorn** [comment]
Not easy enough for me to figure out right now, it seems. :-)

I think I managed to install .NET Core, and I managed to clone the Zilf source code (Debian had some problems with that, but I found a workaround), and I'm guessing that "dotnet build" is the magical command for building. But that's where I run into further problems:

- It complains that it can't find $DOTNET_ROOT/sdk/2.2.300/Microsoft/VisualStudio/v16.0/VSSDK/Microsoft.VsSDK.targets
- It complains that "The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found.

I'll have to look at it again later.

**Comment by eriktorbjorn** [comment]
I guess "dotnet publish" was the incantation I was looking for. The errors I got seem to come from Analyzers, and I don't need that?

It's a bit improvised, but I did manage to build The Witness with it.

So does it fix the crash? Well... yes, and no. It didn't crash immediately, so I went to the front door. There Frotz informed me that the game was trying to do something naughty:

```
The gate is closed. A door bell glows at you, almost daring you to ring it.
Warning: @get_prop called with object 0 (PC = 16e01) (will ignore further
occurrences)
Warning: @move_object called moving into object 0 (PC = 16ebc) (will ignore
further occurrences)
```

Judging by txd, it's here somewhere:

```
16ddd:  PRINT           ", heading toward "
16dea:  CALL            16f40 (L04,L01) -> -(SP)
16df1:  CALL            49ca ((SP)+) -> -(SP)
16df7:  PRINT           "."
16dfa:  NEW_LINE        
16dfb:  JUMP            16eb2
16dfe:  GET_PROP        L01,#04 -> L06
16e02:  JZ              L06 [TRUE] 16eb2
```

Corresponding ZIL code:

```
			      <TELL ", heading toward ">
			      <DIR-PRINT <DIR-FROM .OL .WHERE>>
			      <TELL "." CR>)>)
		      (<AND <SET PCOR <GETP .WHERE ,P?CORRIDOR>>
			    <NOT <==? <BAND .COR .PCOR> 0>>>
```

And here:

```
16e93:  JE              L04,#dd [FALSE] 16ea1
16e97:  PRINT           "the south"
16e9e:  JUMP            16eae
16ea1:  CALL            16f40 (L01,L04) -> -(SP)
16ea8:  CALL            49ca ((SP)+) -> -(SP)
16eae:  PRINT           "."
16eb1:  NEW_LINE        
16eb2:  CALL            16fe2 (L00,L08) -> -(SP)
16eb9:  INSERT_OBJ      L00,L01
16ebc:  LOADW           L03,#00 -> -(SP)
```

Corresponding ZIL-code:

```
		       <COND (<==? .OL ,LIMBO> <TELL "the south">)
			     (T <DIR-PRINT <DIR-FROM .WHERE .OL>>)>
		       <TELL "." CR>)>)>
	 <WHERE-UPDATE .PERSON .FLG>
	 <MOVE .PERSON .WHERE>
	 <COND (<==? <GET .GT ,GOAL-F> .WHERE>
```

Then I rung the bell and went to the Living Room, where...

```
>Z
Time passes...
Suddenly, a clap of thunder rolls across the hills outside.
Fatal error: Store out of dynamic memory
[Hit any key to exit.]
```

I don't know what happened there, but that's _some_ thunderstorm!

So anyway, the newer ZILF compiler does much better, but there are still issues with The Witness.

**Comment by eriktorbjorn** [comment]
Still trying to figure out what's going wrong in The Witness. I thought I'd start with the warning messages when you arrive at the front porch, because that should be easier than the later crash.

One of the warning messages seems to get printed because of something strange happening in FOLLOW-GOAL, when it does ``<SET FLG <MOVE-PERSON .PERSON .LOC>>`` and .LOC is 0.

Both Frotz debugging messages and debug code I added myself points to .PERSON  being the cat at this point. The released version does check if the cat is nearby, by doesn't try to move it.

**Comment by eriktorbjorn** [comment]
I think I've found it.

In people.zil, we have:

```
"Constants used as table offsets for each character, including the player:"

<CONSTANT PLAYER-C 0>
<CONSTANT PHONG-C 1>
<CONSTANT LINDER-C 2>
<CONSTANT STILES-C 3>
<CONSTANT MONICA-C 4>
<CONSTANT CAT-C 5>
<CONSTANT CHARACTER-MAX 5>
```

But in events.zil, we have:

```
"Goal tables for the 6 characters (including PLAYER), offset
by the preceding constants, which, for a given character,
is the P?CHARACTER property of the object."

<GLOBAL GOAL-TABLES
	<TABLE <TABLE <> <> <> <> 1 <> <> I-FOLLOW 4 4>
	       <TABLE <> <> <> <> 1 <> <> I-PHONG 3 3>
	       ;<TABLE <> <> <> <> 1 <> <> I-LINDER 4 4>
	       <TABLE <> <> <> <> 1 <> <> I-STILES 9 9>
	       <TABLE <> <> <> <> 1 <> <> I-MONICA 2 2>
	       ;<TABLE <> <> <> <> 1 <> <> I-CAT 1 1>>>
```

The entries for I-LINDER and I-CAT were commented out in commit https://github.com/AlexProudfoot/The-ZIL-Files/commit/1f8cabf225521896ca6f48c060058eb14eb99618

Restoring them makes the game work much better, even with Zilf 0.8.

**Comment by eriktorbjorn** [comment]
With this change, I was able to play the game all the way to the end, though I skipped all the optional clues. In fact, I never even left Mr. Linder's office.

I did come across one bug, I think. Near the end, after cuffing Monica, you're supposed to search her. Here's what's supposed to happen:

```
>SEARCH MONICA
You find a single key in Monica's pocket and take it.

>SEARCH MONICA
You find a hand gun in Monica's pocket and take it.
```

What actually happens, at least when compiled with Zilf 0.8:

```
>SEARCH MONICA
Monica grudgingly allows you to search. You find nothing whatsoever of
interest.

>SEARCH MONICA FOR KEY
You find a single key in Monica's pocket and take it.

>SEARCH MONICA FOR GUN
You find a hand gun in Monica's pocket and take it.
```

The corresponding source code in people.zil:

```
	<COND (<NOT ,MONICA-TIED-TO> <MONICA-PUSHES>)
	      (<AND <IN? ,CLOCK-KEY ,MONICA>
		    <OR <VERB? SEARCH> <EQUAL? .OBJ ,GENERIC-KEY ,CLOCK-KEY>>>
	       <MOVE ,CLOCK-KEY ,PLAYER>
	       <FCLEAR ,CLOCK-KEY ,INVISIBLE>
	       <FSET ,CLOCK-KEY ,TOUCHBIT>
	       <TELL
"You find a single key in Monica's pocket and take it." CR> ;"? better")
	      (<AND <IN? ,INSIDE-GUN ,MONICA>
		    <OR <VERB? SEARCH><EQUAL? .OBJ ,GENERIC-GUN ,INSIDE-GUN>>>
	       <SETG SEEN-MONICA-AT-CLOCK T>
	       <MOVE ,INSIDE-GUN ,PLAYER>
	       <FCLEAR ,INSIDE-GUN ,INVISIBLE>
	       <FSET ,INSIDE-GUN ,TOUCHBIT>
	       <TELL
"You find a hand gun in Monica's pocket and take it." CR> ;"? better")
	      (T <RFALSE>)>)
```

I'll try the development version of Zilf later, and if it still doesn't work I'll see if I can figure out why.

**Comment by eriktorbjorn** [comment]
I didn't notice until now that I actually get errors if I put back those two entries:

[error ZIL0501] D:\Git\The-ZIL-Files\witness\events.zil:606: non-constant initializer for table element '7': I-LINDER
[error ZIL0501] D:\Git\The-ZIL-Files\witness\events.zil:609: non-constant initializer for table element '7': I-CAT

But it still generated enough .zap files that I was able to build it.

In the original witnessdat.zap, I-LINDER and I-CAT still end up under "USER DEFINED CONSTANTS", both defined as 0.

So for clarity, perhaps simply add this somewhere?

```
<CONSTANT I-LINDER 0>
<CONSTANT I-CAT 0>
```

That way it's still obvious what those table entries are for, and I-LINDER and I-CAT are both defined as 0 in witness_data.zap.

**Comment by eriktorbjorn** [comment]
I've created a pull request: https://github.com/AlexProudfoot/The-ZIL-Files/pull/74

**Comment by eriktorbjorn** [comment]
I've made a separate issue for the problem with searching Monica: https://github.com/AlexProudfoot/The-ZIL-Files/issues/77

I first took it for a compiler bug, but then I noticed that the .zip file in Jason Scott's repository has the same problem. I guess that's a... relief?

**Comment by AlexProudfoot** [comment]
I’ve used an alternate solution in The Infocom Files. In all such cases, instead of just commenting out, I also replace the undefined elements with nulls. The Infocom Files version of The Witness no longer crashes.
